### ISSUE TITLE
Use of `AtomicPtr` in `unsafe_ifunc` prevents memchr from being inlined when compiled with avx enabled

### ISSUE THREAD

**Issue by redzic** [BurntSushi/memchr#100]
`is_x86_feature_detected!` resolves to just a `return true` when `-C target-cpu` or `-C target-feature` is set to a value that enables the feature. When using just a simple `is_x86_feature_detected!` and `-C target-cpu=native` (or whatever), the compiler can inline the function and completely avoid the machinery of the atomic operations and calling a function pointer. However, when using `AtomicPtr`, it is impossible for the compiler to inline the function at all.

It would be great if there was some way to automatically disable the runtime feature detection if avx (or whatever the corresponding CPU feature set is) is already enabled at compile-time.

**Comment by BurntSushi** [comment]
Thanks for the issue, but:

1. To make a decision here, I would want to see a proposal for what to do. I'm more likely to accept something simple.
2. Additionally, I would want to see a real benchmark where this matters. It's worth pointing out that memchr itself is quite large, and inlining it may be unwise.
3. memchr is traditionally called from a dynamically linked libc, which means inlining is never possible there anyway and that seems to be accepted by folks?

Overall, I basically want better justification that this with real use cases.

**Comment by redzic** [comment]
I will try to do some benchmarks later, but one use case of inlining memchr is that it could allow LLVM to specialize the function for haystacks with statically-known lengths, which might be useful for small size arrays. For example: https://godbolt.org/z/qxf5GbqYr

**Comment by BurntSushi** [comment]
I don't think a solid justification has been shown here. I get that inlining helps with things that inlining usually helps with, but there are other concerns here. First is that there is a lot of code in the `memchr` routines for LLVM to see through, so ti's not totally clear how well such optimizations would apply. Second is that there is likely some code complexity involved here.

With that said, if one wanted to submit a _simple_ patch that gets rid of the runtime detection shenanigans when it's known that the target feature is enabled at compile time, then I'd be very open to that.

**Comment by BurntSushi** [comment]
This is perhaps partially addressed by #120, but it only takes effect when `std` is disabled.
