### ISSUE TITLE
Provide const implementation

### ISSUE THREAD

**Issue by chrysn** [BurntSushi/memchr#104]
As const evaluation is slowly becoming powerful enough for wide use, `memchr` not providing a const version is slowly becoming an issue.

For example, in https://github.com/Amanieu/cstr_core/pull/25 (an embedded version of `cstr`), it would be convenient to construct a &str out of const array data taken from C in mixed C-and-Rust environments. The workaround there is to have an own simple-stupid-but-const memchr implementation and dispatch through [`const_eval_select`](https://doc.rust-lang.org/stable/core/intrinsics/fn.const_eval_select.html) between that and an actually runtime-friendly memchr from this crate.

On the long run, it would be great if this crate would just provide its memchr as const -- obviously that's not gonna fly any time soon (especially considering the MSRV), but there could be steps:
* This crate could provide a `memchr_const` function (feel free to take [the one from there](https://github.com/Amanieu/cstr_core/pull/25/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R52) if you like, it's under a different license but I wrote it and hereby also license it under this crate's license).
* This crate could provide an auto-dispatching `memchr` under a nightly-only feature gate.

The full solution (memchr "just" being const) is likely to be tricky, because while a "regular" memchr can be const on stable in the forseeable future, I don't expect that to happen for vectorized or even libc-calling versions. Thus, once any of these optimizations are on, dispatch between the runtime-and-optimized and the const version will still need to happen, and the only way to do that currently AFAIK is through const_eval_select which there are no plans for stabilization for. This issue could be a use case to start stabilizing const_eval_select, or explore alternative avenues.

**Comment by BurntSushi** [comment]
Correct me if I'm wrong here, but it kind of seems like to me that the biggest win here would be an auto-dispatching routine. (This is the first I'm learning about the possibility of such a thing.) Without that, it doesn't really seem like adding a `memchr_const` routine carries its weight IMO. But maybe I'm wrong.

The other consideration here is that I generally don't add nightly-only things to crates I maintain. I've done it in the past, and it has usually bitten me from a maintenance perspective. So while I'm not completely opposed to it, I think I would want a really compelling reason to do it. I don't think I see one here: the work around looks like a little bit of non-hairy code.

> As const evaluation is slowly becoming powerful enough for wide use, memchr not providing a const version is slowly becoming an issue.

From what I've seen here, I would qualify "becoming an issue" with "a minor annoyance." Do you think that's fair? Or am I missing something here? Is this issue appearing elsewhere?

**Comment by chrysn** [comment]
> From what I've seen here, I would qualify "becoming an issue" with "a
> minor annoyance." Do you think that's fair?

Yes, this is wishlist level. It's not like it breaks anything, it's just
that the more one uses const, the more one finds things that could be
const in theory lacking.

> Correct me if I'm wrong here, but it kind of seems like to me that the
> biggest win here would be an auto-dispatching routine. (This is the
> first I'm learning about the possibility of such a thing.) Without
> that, it doesn't really seem like adding a `memchr_const` routine
> carries its weight IMO. But maybe I'm wrong.

If we get auto-dispatching in the first bout, then yes the memchr_const
is moot. But depending on maybe-never-stabilized behavior (even for a
nightly feature) may be controversial, and if it is, then having a
memchr_const allows users of the memchr crate to use some memchr even
for const contexts (eg. make the choice to use this one as performance
does not matter but correctness does and most use cases are const
anyway), or to build the 4-line const-dependent dispatch on their own.

> [nightly-only but] the work around looks like a little bit of non-hairy code.

That'd a perfectly understandable stance; in that case I hope that
discussion here can serve as guidance to other users, and possibly as a
source for a copy-pastable workaround (because non-hairy doesn't mean
one can't get it wrong easily, screwed something up myself on the first
round).

> The other consideration here is that I generally don't add
> nightly-only things to crates I maintain.

A minimal (probably inefficient-at-runtime) memchr can already be
written const starting from 1.46 (the one above works there), the hard
nightly-only thing is the dispatch.

If const_eval_select were proposed for stabilization, would you consider
the use in this crate a suitable example showcase? (Not much point in
proposing that on the language level with "and then we can have a memchr
that works everywhere" and that crate's maintainer saying "meh" even to
the use in that crate, independent of how the rest of the proposal turns
out).

-- 
To use raw power is to make yourself infinitely vulnerable to greater powers.
  -- Bene Gesserit axiom

**Comment by BurntSushi** [comment]
> If we get auto-dispatching in the first bout, then a pub memchr_const is moot. But depending on maybe-never-stabilized behavior (even for a nightly feature) may be controversial, and if it is, then having a memchr_const allows users of the memchr crate to use some memchr even for const contexts (eg. make the choice to use this one as performance does not matter but correctness does and most use cases are const anyway), or to build the 2-line const-dependent dispatch on their own.

Yeah from what I can tell, I don't think I'd be willing to bring in the auto-dispatching stuff given that it's both unstable and doesn't appear to have any clear path to stability any time soon. So if you're building this on your own, then I think it's also reasonable to write the const version of `memchr` as well. I don't think there's too much benefit to including it in this crate. 

> If const_eval_select were proposed for stabilization, would you consider the use in this crate a suitable example showcase? (Not much point in proposing that on the language level with "and then we can have a memchr that works everywhere" and that crate's maintainer saying "meh" even to the use in that crate, independent of how the rest of the proposal turns out).

I _think_ so. To be honest, it's not totally clear to me how broadly useful it would be. But what it provides _seems_ like a strictly better thing than what is provided today, and it looks like it can be done without much work. So that seems like something I'd be okay with.

The one caveat I'd add is whether it's actually sound to do it. I've read the safety argument on `const_eval_select`, and everything _seems_ okay, but I am not an expert in reasoning about the safety requirements of such a thing. For example, if `memchr` does a CPUID check and that in turn uses atomics to cache the CPUID check, then does that violate referential transparency? I would _guess_ not. It certainly doesn't seem like it violates it from a logical perspective, but it's worth being sure about it, especially if the existence of the public API of memchr being const depends on it.

**Comment by BurntSushi** [comment]
I'm going to close this because it isn't clear to me that there are any obvious next steps for this crate in the near future.

I'd be happy to revisit this if things change.
