### ISSUE TITLE
Build script flagged as Virus by Kaspersky Endpoint Security

### ISSUE THREAD

**Issue by birdistheword96** [BurntSushi/memchr#113]
Unable to use any crates that have memchr as a dependency (such as the regex module) as Kaspersky Endpoint Security flags the build script as a virus:
![image](https://user-images.githubusercontent.com/53791523/177127387-815e3b53-e771-4459-b506-f761778c3fcf.png)

**Comment by BurntSushi** [comment]
Thanks for the heads up, but the problem isn't with this crate. The problem is in the software that falsely detects this crate as malicious.
