### ISSUE TITLE
Feature request: no-std + alloc

### ISSUE THREAD

**Issue by VorpalBlade** [BurntSushi/memchr#121]
I was looking through the code of this crate. I have a need for something like this on a no-std + alloc target, but it seems several features (such as using `Cow ` from alloc) are missing. That should be possible to support.

**Comment by BurntSushi** [comment]
Can you say specifically what features you need? And also why you can't enable std?

**Comment by VorpalBlade** [comment]
First: See my comment in issue #122.

Second: It is probable I could make do without `Cow` (my primary issue was #122, I just discovered this as well while investigating how difficult the limitations were and thought it would be nice to improve the API).

**Comment by BurntSushi** [comment]
Aye. Yes, this is definitely something we should do.

I _believe_ the only API that's added with `alloc` is [`Finder::into_owned`](https://docs.rs/memchr/latest/memchr/memmem/struct.Finder.html#method.into_owned).

(I don't think there is any `Cow` in the public API of this crate, FWIW.)
