### ISSUE TITLE
`Memchr<'_>` is no longer `Sync` from v2.6

### ISSUE THREAD

**Issue by Nugine** [BurntSushi/memchr#133]
Test code:

```rust
use memchr::memchr_iter;

pub fn assert_sync<T: Sync>(_: &T) {}

pub fn foo(input: &[u8]) {
    assert_sync(&memchr_iter(b'\n', input));
}
```

See also https://github.com/Nugine/s3s/issues/79

**Comment by conradludgate** [comment]
For further reference, in version 2.5.0 it was Send/Sync and in 2.6.0 it is now !Send/!Sync

**Comment by marregui** [comment]
I am thinking this fix deserves a t-shirt

**Comment by BurntSushi** [comment]
This is fixed on crates.io in `memchr 2.6.2`.
