### ISSUE TITLE
Update Cargo.toml `package.description`

### ISSUE THREAD

**Issue by bnoctis** [BurntSushi/memchr#138]
It's (still?) "Safe interface to memchr", which indicates a wrapper for memchr(3), but the docs explicitly declares it's not tied to that.

**Comment by BurntSushi** [comment]
Good point. I rarely revisit the description of a crate once it is published. This crate in particular has evolved significantly from its [original implementation](https://github.com/BurntSushi/memchr/blob/e9a2a1830d97205424b9b45d65f001ac6b403c04/src/lib.rs#L32-L44).
