### ISSUE TITLE
Cannot compile with thin-lto on MinGW

### ISSUE THREAD

**Issue by clubby789** [BurntSushi/memchr#145]
This is a rustc [issue](https://github.com/rust-lang/rust/issues/109797), but I thought it might help to be aware of this 🙂 
`memchr@2.6.0+` does not link when using thin-lto on MinGW, due to the use of `#[inline]` on functions containing `static`s. The error this causes when using 2.6+ as a dependency of rustc std can be seen [here](https://github.com/rust-lang/rust/pull/121465#issuecomment-1960128112)

https://github.com/BurntSushi/memchr/blob/cedf318090876c6d557f234b158dd4fdc91c41ec/src/arch/x86_64/memchr.rs#L173-L180
https://github.com/BurntSushi/memchr/blob/cedf318090876c6d557f234b158dd4fdc91c41ec/src/arch/x86_64/memchr.rs#L74

**Comment by BurntSushi** [comment]
Yeah I'm aware. If there's a simple patch to fix this, I'd accept it, but I otherwise don't think it's worth tracking here since it's already tracked on rustc.
