### ISSUE TITLE
`memchr4`

### ISSUE THREAD

**Issue by turalcar** [BurntSushi/memchr#148]
I found myself needing one. This was brought up several years ago in https://github.com/BurntSushi/memchr/issues/11 and https://github.com/BurntSushi/memchr/issues/38. I'm just wondering if anything changed since then.

**Comment by BurntSushi** [comment]
Nothing has changed. Someone has to litigate the experiment. I am unlikely to do it myself any time soon. If someone wants support for `memchr4`, then they will need to:

* Add it as a new routine.
* Add support for it to the benchmark harness.
* Do an analysis of how it compares versus the naive implementation of `memchr4`.
* If the SIMD version is a measurably and ideally significant improvement over the naive version, then I'd probably be okay accepting it into the crate as a new API.
