### ISSUE TITLE
memchr 2.4.0 msrv breaks nom 5.1.2 msrv of 1.37

### ISSUE THREAD

**Issue by ericseppanen** [BurntSushi/memchr#83]
See https://github.com/Geal/nom/issues/1313.

`nom 5.1` depends on `memchr = "^2.0". It has a documented msrv of 1.37.

Since 2.4.0 is supposed to be semver-compatible, cargo will select `memchr` `2.4.0`, which does not build on 1.37.

I understand that balancing msrv vs semver can be a drag on maintainer productivity, so I have no real expectations here other than documenting that it happened.

**Comment by BurntSushi** [comment]
Yes, this was done explicitly: https://github.com/BurntSushi/memchr/commit/952717e1c370693ae68777b0c9367bd31bd8fb03

If you have MSRV constraints, then you can use an older version of memchr in your final artifact.

**Comment by BurntSushi** [comment]
See also: https://github.com/BurntSushi/memchr#minimum-rust-version-policy
