### ISSUE TITLE
The next function in memchr*_iter doesn't seem to compute efficiently.

### ISSUE THREAD

**Issue by yiunsr** [BurntSushi/memchr#88]
I am trying to make an efficient csv parser using memchr.

I want to search all commas when there is a line like the one below.
a1,b1,c1,d2
In this case, I want to use the code below.

let sep_iter = memchr3_iter(col_sep, row_sep, b'\'', &buffer[..]);
...
loop {
     let next_sep_pos_wrap = self.sep_iter.next();
     .....
}

If sep_iter.next() is calculated here, it seems that the already calculated result can be used again, but it seems to recalculate from the beginning.
When sep_iter.next() operates for the first time, it seems that the result value is already stored in another bit. But now it seems to only use trailing_zeros.

**Comment by BurntSushi** [comment]
Sorry, but I don't understand what it is you're asking or what specifically you're saying is "inefficient" about `next()`. Perhaps you can propose a change to the code?

https://github.com/BurntSushi/memchr/blob/186ac04b6fd52f2f7effa5ba7f11f1bb4c4a8a26/src/memchr/iter.rs#L3-L21

> I am trying to make an efficient csv parser using memchr.

Why not use the `csv` crate?

> I want to search all commas when there is a line like the one below.
> a1,b1,c1,d2

This is unlikely to be a good fit for memchr. It's likely that the haystacks will be too short and you'll get hit too hard with memchr's overhead.

**Comment by yiunsr** [comment]
> Sorry, but I don't understand what it is you're asking or what specifically you're saying is "inefficient" about next(). Perhaps you can propose a change to the code?

Yes, I think the next function could be improved more efficiently.


For example, when the following code works
```
let haystack = b"1,a1,b11,c111,d1111,e11111\n2,a2,b22,c222,d2222,e22222";
let mut it = memchr3_iter(b',', b'\t', b'\n', haystack);
it.next();  // 1st next
it.next();  // 2nd next
it.next();  // 3rd next
```


https://github.com/BurntSushi/memchr/blob/186ac04b6fd52f2f7effa5ba7f11f1bb4c4a8a26/src/memchr/x86/avx.rs#L576-L602

```
let mask1 = _mm256_movemask_epi8(eq1);
let mask2 = _mm256_movemask_epi8(eq2);
let mask3 = _mm256_movemask_epi8(eq3);
let total_mask = mask1 | mask2 | mask3;
```

The **total_mask** value is the result of checking whether a needle exists in a 32-byte string. **total_mask** is the result of parallel computation.

'total_mask' is 10010000 00001000 00100001 00010010 in binary.
'1st next' is total_mask.trailing_zeros() = > 1

total_mask &=  !(1 << (bit_pos));    => 10010100 00001000 00100001 00010000
'2nd next' is total_mask.trailing_zeros() => 4


total_mask &=  !(1 << (bit_pos));    => 10010100 00001000 00100001 00000000
'3rd next' is total_mask.trailing_zeros()   => 8

If the total_mask value is stored in the cache, this value can be used in the next function.
In particular, if there are many needles within 32 bytes, there will be more speed improvement. 
In a csv file, many commas (or tabs) can exist within 32 bytes.


I'm making a program called lightsheet(https://github.com/yiunsr/lightsheet_rust), and I'm trying to reduce the time to insert a very large csv file into sqlite database. The reason I want to make a separate csv parser using memchr is to use simd(avx). I want to improve the csv parser while using simd in the rust stable.

**Comment by yiunsr** [comment]
I made a new library(https://github.com/yiunsr/bufchr)  that I modified to be suitable for csv parsing. I used the cache suggested above.
