### ISSUE TITLE
api argument order inconsitant

### ISSUE THREAD

**Issue by Stargateur** [BurntSushi/memchr#92]
I saw sometime `haystack` is in first then `needle` is second like in https://docs.rs/memchr/2.4.1/memchr/memmem/fn.find.html. But sometime it's the opposite like https://docs.rs/memchr/2.4.1/memchr/struct.Memchr.html#method.new.

That can lead to make error.

**Comment by BurntSushi** [comment]
Yes, it's regrettable. I switched it for `memmem` to match the corresponding libc routine. Unfortunately, I didn't do the same for `memchr` back when I made it.

I don't have any plans at this time to release a `memchr 3` and this change isn't enough to motivate that.

If and when I do a `memchr3`, the full public API will be revisited and it's likely that the memchr routines will also be renamed to `find` like the `memmem` routines.

**Comment by Stargateur** [comment]
I mostly agree but I do not get why close this, cause you agree this is an issue. Even if you don't plan to fix it any soon.
